name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.md"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Prepare Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore.jks

      - name: Build Release APK
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
        run: gradle assembleRelease

      - name: Rename APK
        run: |
          APK_PATH=$(find app/build/outputs/apk/release -maxdepth 1 -name '*.apk' | head -n 1)
          OUTPUT_FILE="clean-social-link.apk"
          cp "$APK_PATH" "app/build/outputs/apk/release/$OUTPUT_FILE"
          echo "OUTPUT_APK=$OUTPUT_FILE" >> "$GITHUB_ENV"

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: clean-social-link
          path: app/build/outputs/apk/release/${{ env.OUTPUT_APK }}
